### ISSUE TITLE
TypeError: GM_util.getPreferredLocale is not a function (Firefox 54 + intl.locale.matchOS=true)

### ISSUE THREAD

**Issue by jbeich** [greasemonkey/greasemonkey#2488]
GM fails to install scripts on Nightly but when upgrading with some already installed the following errors shows up on console. [matchOS check](https://github.com/greasemonkey/greasemonkey/blob/696848acc40c/modules/util/getPreferredLocale.js#L10) probably needs to be adjusted per [bug 1337551](https://bugzilla.mozilla.org/show_bug.cgi?id=1337551) + [bug 1344901](https://bugzilla.mozilla.org/show_bug.cgi?id=1344901). CC @zbraniecki just in case.

```
1489301732457   addons.manager  ERROR   Exception calling provider <unnamed-provider>.getAddonsByTypes: TypeError: GM_util.getPreferredLocale is not a function (chrome://greasemonkey-modules/content/script.js:148:9) JS Stack trace: getBestLocalization@script.js:148:9 < Script_getLocalizedDescription@script.js:156:20 < ScriptAddon@addons4.js:98:3 < ScriptAddonFactoryByScript@addons4.js:74:28 < AddonProvider_getAddonsByTypes/<@addons4.js:50:27 < AddonProvider_getAddonsByTypes@addons4.js:49:7 < callProviderAsync@AddonManager.jsm:294:12 < promiseCallProvider/<@AddonManager.jsm:318:53 < Promise@Promise-backend.js:390:5 < promiseCallProvider@AddonManager.jsm:317:10 < getAddonsByTypes/<@AddonManager.jsm:2510:36
```

**Comment by janekptacijarabaci** [comment]
Thank you.

**Comment by zbraniecki** [comment]
I'm not sure why you want to get system locale as preferred one rather than app locale.

And if you, by any chance, do want an app locale, please, wait for bug 1346819 to land (hopefully today) and then use `Services.locale.getAppLocaleAsLangTag`.

Thank you and sorry for the trouble!

**Comment by arantius** [comment]
I've just pushed version 3.11beta1: https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/versions/beta?page=1#version-3.11beta1

It would be very useful if you could install it and confirm that it fixes this issue.

**Comment by jbeich** [comment]
I confirm, FF55 + `intl.locale.matchOS=true` works fine on GM 3.11beta1 unlike GM 3.10.
