### ISSUE TITLE
Edit script stops working

### ISSUE THREAD

**Issue by alice0775** [greasemonkey/greasemonkey#2321]
Build Identifier:
https://hg.mozilla.org/releases/mozilla-aurora/rev/d02de1b2320dfb3ff45b80d5e5620011a10d375c
Mozilla/5.0 (Windows NT 6.1; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0 ID:20151101004142

Edit script stops working on Firefox44.0a2 + GraseMonkey3.5.
However,  It works on Firefox42.0build2 with the same profile..

The following Error are shown in "Browser Console" when I choose "Edit".

------------------------------
While creating services from category 'profile-after-change', service for entry 'Sapi Speech Synth', contract ID '@mozilla.org/synthsapi;1' does not implement nsIObserver.

Failed to load module chrome://greasemonkey-modules/content/util/openInEditor.js. XPCOMUtils.jsm:279:0

NS_ERROR_FILE_NOT_FOUND: Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [nsIXPCComponents_Utils.import] openInEditor.js:7:0
---------------------------

**Comment by janekptacijarabaci** [comment]
Dupe of #2304
This is already fixed in the nightly: https://arantius.com/misc/gm-nightly/
