### ISSUE TITLE
"Components.utils.cloneInto is not a function" Error while calling GM_xmlhttpRequest

### ISSUE THREAD

**Issue by pwlin** [greasemonkey/greasemonkey#2284]
My apologies if this is discussed before, but it seems like GM_xmlhttpRequest does not work anymore.

A simple 
```javascript
// ==UserScript==
// @name        test xmlhttp
// @namespace   http://example.com/
// @include     http://wiki.greasespot.net/GM_xmlhttpRequest
// @version     1
// @grant       GM_xmlhttpRequest
// ==/UserScript==

GM_xmlhttpRequest({
  method: "GET",
  url: "http://www.google.com/",
  onload: function(response) {
    alert(response.responseText);
  }
});
```
Fails with:
`Components.utils.cloneInto is not a function`
`chrome://greasemonkey-modules/content/xmlhttprequester.js (Line 303)`

It happens with Greasemonkey `3.3.*` as well as `3.4.*` on Firefox ESR (35)

**Comment by arantius** [comment]
Can you test on a newer version of Firefox?  Does that work any better?

**Comment by pwlin** [comment]
It works correctly on both current Firefox `40.0.3` (latest release) and also on Nightly (`44.0a1`).

So somewhere along the way, this bug is introduced. The strange thing is that this error also occure with Greasemonkey `3.2` which supposedly is compatible with Firefox 3.5

As Firefox ESR is still not that obscure, is there anything we can do here?

**Comment by pwlin** [comment]
I am sorry, something is definitely wrong on my configuration. I am closing this issue. Sorry for false alarm.
