### ISSUE TITLE
Palemoon & google-hit-hider-by-domain-search-filter-block-sites script

### ISSUE THREAD

**Issue by delicacy1** [greasemonkey/greasemonkey#2193]
Error console:
Error: Components.utils.cloneInto is not a function
Source File: resource://greasemonkey/xmlhttprequester.js
Line: 93

Palemoon 25.4.1

Plus:

with https://greasyfork.org/en/scripts/1682-google-hit-hider-by-domain-search-filter-block-sites

there's an icon that appears on the right
side of google pages, the program's options window.. if you click on it,
go to "block" section", click on "bigresource.com" (to unblock appears), then clicking on "save lists" should make bigresource.com disappear. this is true with greasemonkey 2.0, & doesn't work on 3.2

**Comment by delicacy1** [comment]
even worse, nothing is saved with the script, when i restart pale moon

**Comment by arantius** [comment]
Pale Moon is not officially supported.

**Comment by janekptacijarabaci** [comment]
@delicacy1: See https://github.com/greasemonkey/greasemonkey/issues/2182 (it refers to both things)

**Comment by delicacy1** [comment]
palemoon is the non "bloated" version of firefox, reports have been made about incompatibility issues
with palemoon before & aimlessly..

life is short.
